config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
  # resources :movies

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
end

# resources :lists, only: [:index] do
#   resources :bookmarks, only: [:new, :create]
# end
# resources :bookmarks, only: [:destroy]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie, presence: true
  validates :list, presence: true

  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path, notice: 'Bookmark was successfully destroyed.'
  end

  private

  def set_list
    @list = List.find_by(id: params[:list_id])
    if @list.nil?
      redirect_to lists_path, alert: 'List not found.'
    end
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.includes(:movies).find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:success] = "Object successfully created"
      redirect_to list_path(@list)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h2>Add a new bookmark to <%= @list.name %></h2>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.error_notification %>
  <%= f.association :movie, label_method: :title, value_method: :id, include_blank: false %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <div class="nav-container">
        <div class="popcorn-home">
          <%= link_to image_tag("3418886.png", alt: "Popcorn"), lists_path %>
        </div>
          <div class="links-home">
            <%= link_to 'My Lists', lists_path %>
            <%= link_to 'New List', new_list_path %>
        </div>
      </div>
  </nav>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2luJUMzJUE5bWF8ZW58MHx8MHx8fDA%3D)">
  Save any kind of movies
</div>


<div class="banner-lists">
  <h1><strong>All lists</strong></h1>
  <button type="button" class="btn btn-success"><%= link_to "Add a new list", new_list_path %></button>
</div>

<div class="container mt-3">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <%= image_tag("matrix.jpg", class: "card-img-top") %>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to 'View List', list_path(list), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Add a new List</h1>


<div class="te mt-3">
  <%= form_with model: @list, class: "needs-validation", novalidate: true do |f| %>

    <div class="form-group mb-2">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter List name " %>
    </div>

    <div class="boutons">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Back to list", lists_path, class: "btn btn-secondary mt-2" %>
    </div>
<% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>


<div class="movies-grid">
  <% @list.movies.each do |movie| %>
    <% bookmark = @list.bookmarks.find_by(movie_id: movie.id) %>
    <div class="card-trip">
      <% if movie.poster_url.present? %>
        <img src="<%= movie.poster_url %>" alt="<%= movie.title %>" class="card-trip-image" />
      <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= movie.title %></h2>
          <p><%= movie.overview %></p>
          <% if bookmark.present? %>
            <p>Bookmark: <%= bookmark.comment %></p>
          <% end %>
        </div>
        <h2 class="card-trip-pricing">Rating: <%= movie.rating %></h2>
      </div>
    </div>
  <% end %>
</div>










<button type="button" class="btn btn-outline-secondary"><%= link_to "Back to all Lists", lists_path %></button>
<%= link_to 'Add a movie', new_list_bookmark_path(@list), class: 'btn btn-primary' %>

app/views/movies/index.html.erb
<div class="banner d-flex p-2 justify-content-between">
  <h1>All Movies</h1>
</div>

<div class="all-cards">
<% @movies.each do |movie| %>
<div class="card mb-3" style="width: 18rem;">
<img class="card-img-top" src= <%= movie.poster_url %> alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><strong><%= movie.title %></strong></h5>
    <p class="card-text"><%= movie.overview %></p>
    <p class="card-text"><%= movie.rating %></p>
    <p class="card-text"></p>
  </div>
</div>
  <% end %>
</div>